name: unibe_app_control
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.17.5
  excel: ^2.0.6
  file_picker: ^5.0.1
  qr_flutter: ^4.0.0
  provider: ^6.1.2
  http: ^1.2.2
  camera: 0.10.0+2
  qr_code_scanner: ^1.0.0
  firebase_storage: ^11.0.0
  image_picker: ^0.8.7+5
  image: ^3.0.1
  url_launcher: ^6.0.20
  android_intent_plus: ^2.0.6
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: false
  image_path: "images/unibe_logo_am.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - images/logo_unibe.png
    - images/logo_unibe_dos.jpg
    - images/unibe_logo_am.png
    - images/carnet.png
    - images/default_profile.png

