// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlfxoBBoznCsmXbjXd1t1XkbfSwu1kCg',
    appId: '1:715882159378:web:d23ae4e5520a72e82b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    authDomain: 'controlacceso-403b0.firebaseapp.com',
    databaseURL: 'https://controlacceso-403b0-default-rtdb.firebaseio.com',
    storageBucket: 'controlacceso-403b0.appspot.com',
    measurementId: 'G-3W9RDE6RBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJRJ8gVSUOuG52Dna3J965cBOM271S0I',
    appId: '1:715882159378:android:369871a164ba431c2b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    databaseURL: 'https://controlacceso-403b0-default-rtdb.firebaseio.com',
    storageBucket: 'controlacceso-403b0.firebasestorage.app', // Cambiado aquí
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVzJBH_dAOtwZY_gIZ3cersauw-8rB5-o',
    appId: '1:715882159378:ios:c989f96b9abe01992b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    databaseURL: 'https://controlacceso-403b0-default-rtdb.firebaseio.com',
    storageBucket: 'controlacceso-403b0.appspot.com',
    iosBundleId: 'com.example.unibeAppControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVzJBH_dAOtwZY_gIZ3cersauw-8rB5-o',
    appId: '1:715882159378:ios:c989f96b9abe01992b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    databaseURL: 'https://controlacceso-403b0-default-rtdb.firebaseio.com',
    storageBucket: 'controlacceso-403b0.appspot.com',
    iosBundleId: 'com.example.unibeAppControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKlfxoBBoznCsmXbjXd1t1XkbfSwu1kCg',
    appId: '1:715882159378:web:b4e15906d569f6502b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    authDomain: 'controlacceso-403b0.firebaseapp.com',
    databaseURL: 'https://controlacceso-403b0-default-rtdb.firebaseio.com',
    storageBucket: 'controlacceso-403b0.appspot.com',
    measurementId: 'G-MXF9M7PE1W',
  );
}
