// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlfxoBBoznCsmXbjXd1t1XkbfSwu1kCg',
    appId: '1:715882159378:web:d23ae4e5520a72e82b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    authDomain: 'controlacceso-403b0.firebaseapp.com',
    storageBucket: 'controlacceso-403b0.appspot.com',
    measurementId: 'G-3W9RDE6RBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJRJ8gVSUOuG52Dna3J965cBOM271S0I',
    appId: '1:715882159378:android:369871a164ba431c2b67cb',
    messagingSenderId: '715882159378',
    projectId: 'controlacceso-403b0',
    databaseURL: 'https://controlacceso-403b0-default-rtdb.firebaseio.com',
    storageBucket: 'controlacceso-403b0.appspot.com', // Corregido
  );
}
