name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Ajusta si usas otra rama como "master"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      # Paso 3: Instalar dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # Paso 4: Construir la aplicación Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Paso 5: Desplegar a Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTROLACCESO_403B0 }}"
          channelId: live
          projectId: controlacceso-403b0
