name: Deploy Flutter Web to Firebase Hosting on Merge

on:
  push:
    branches:
      - main # Cambia si usas otra rama como "master"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Flutter con la misma versión que usas localmente
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: stable

      # Instalar dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # Construir la aplicación Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Desplegar a Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTROLACCESO_403B0 }}"
          channelId: live
          projectId: controlacceso-403b0
